name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  
  pull_request:
    branches: [ "main" ]

permissions:
  id-token : write
  contents : read
  pull_requests : read

  #########
  ### PR ---> Main -- Validate + plan --

  jobs:
   pr-plan:
     if: github.event_name == 'pull_request'
     name: executing the PR
     runs-on: ubuntu-latest
     permissions:
      contents: read
      id-token: write # This is crucial for requesting the OIDC ID token
     steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.ROLE_ARN_DEV }} # Replace with your Role ARN
          aws-region: us-east-1 # Replace with your desired AWS region

      - name: set up terraform
        uses: hashicorp/setup-terraform@v3
      - name: terraform fmt
        run : terraform fmt --check -recursive
      - name: terraform init
        run : terraform init 
      - name: terraform Validate
        run : terraform validate
      - name : terraform plan
        run: terraform plan --var-file=env/dev/dev.tfvars
 
     
